version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 9428:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frontend:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3