version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 9428:8000
    volumes:
      - backend_data:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    volumes:
      - frontend_data:/app/dist/front-end
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3